package com.personal.weathering.presentation.ui.theme
import androidx.compose.ui.graphics.Color

val weatheringBlue = Color(0xFF77D1FF)
val weatheringDarkBlue = Color(0xFF191C1E)
val weatheringDarkBlue70p = Color(0xFF191C1E).copy(alpha = .7f)
val weatheringDarkBlue3p = Color(0xFF191C1E).copy(alpha = .03f)


val onSurfaceLight70p = Color(0xFF171C1F).copy(alpha = .7f)
val surfaceLight30p = Color(0xFFF6FAFE).copy(alpha = .3f)

val clearDaySkyPrimary = Color(0xFFFFF2E2)
val clearDaySkySecondary = Color(0xFFA2D2FF)
val clearNightSkyPrimary = Color(0xFFC6DDFF)
val clearNightSkySecondary = Color(0xFF2C659B)
val partlyCloudyPrimary = Color(0xFFC0DFFF)
val partlyCloudySecondary = Color(0xFFCCCCCC)
val fogPrimary = Color(0xFFE0E0E0)
val fogSecondary = Color(0xFFCCCCCC)
val drizzlePrimary = Color(0xFFF0F8FF)
val drizzleSecondary = Color(0xFFCFD9DF)
val freezingDrizzlePrimary = Color(0xFFB0D0E6)
val freezingDrizzleSecondary = Color(0xFF98C1D9)
val rainPrimary = Color(0xFFA4C8D9)
val rainSecondary = Color(0xFF86B8D9)
val freezingRainPrimary = Color(0xFF98C1D9)
val freezingRainSecondary = Color(0xFF80AADC)
val snowFallPrimary = Color(0xFFF8F8FF)
val snowFallSecondary = Color(0xFFCFD9DF)
val snowGrainsPrimary = Color(0xFFF0F8FF)
val snowGrainsSecondary = Color(0xFFCFD9DF)
val rainShowerPrimary = Color(0xFFCFD9DF)
val rainShowerSecondary = Color(0xFF4682B4)
val snowShowerPrimary = Color(0xFFF8F8FF)
val snowShowerSecondary = Color(0xFFBCBCBC)
val thunderstormPrimary = Color(0xFFCFD9DF)
val thunderstormSecondary = Color(0xFF385F7E)
val thunderstormWithHailPrimary = Color(0xFFCFD9DF)
val thunderstormWithHailSecondary = Color(0xFF4D6777)

val primaryLight = Color(0xFF1A6585)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFC2E8FF)
val onPrimaryContainerLight = Color(0xFF001E2C)
val secondaryLight = Color(0xFF4E616D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD1E5F3)
val onSecondaryContainerLight = Color(0xFF091E28)
val tertiaryLight = Color(0xFF605A7D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE5DEFF)
val onTertiaryContainerLight = Color(0xFF1C1736)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF6FAFE)
val onBackgroundLight = Color(0xFF171C1F)
val surfaceLight = Color(0xFFF6FAFE)
val onSurfaceLight = Color(0xFF171C1F)
val surfaceVariantLight = Color(0xFFDCE3E9)
val onSurfaceVariantLight = Color(0xFF41484D)
val outlineLight = Color(0xFF71787D)
val outlineVariantLight = Color(0xFFC0C7CD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C3134)
val inverseOnSurfaceLight = Color(0xFFEDF1F5)
val inversePrimaryLight = Color(0xFF8ECFF2)
val surfaceDimLight = Color(0xFFD6DADE)
val surfaceBrightLight = Color(0xFFF6FAFE)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F4F8)
val surfaceContainerLight = Color(0xFFEAEEF2)
val surfaceContainerHighLight = Color(0xFFE5E9ED)
val surfaceContainerHighestLight = Color(0xFFDFE3E7)

val primaryDark = Color(0xFF8ECFF2)
val onPrimaryDark = Color(0xFF003549)
val primaryContainerDark = Color(0xFF004D68)
val onPrimaryContainerDark = Color(0xFFC2E8FF)
val secondaryDark = Color(0xFFB5C9D7)
val onSecondaryDark = Color(0xFF20333D)
val secondaryContainerDark = Color(0xFF364954)
val onSecondaryContainerDark = Color(0xFFD1E5F3)
val tertiaryDark = Color(0xFFC9C1EA)
val onTertiaryDark = Color(0xFF312C4C)
val tertiaryContainerDark = Color(0xFF484264)
val onTertiaryContainerDark = Color(0xFFE5DEFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1417)
val onBackgroundDark = Color(0xFFDFE3E7)
val surfaceDark = Color(0xFF0F1417)
val onSurfaceDark = Color(0xFFDFE3E7)
val surfaceVariantDark = Color(0xFF41484D)
val onSurfaceVariantDark = Color(0xFFC0C7CD)
val outlineDark = Color(0xFF8A9297)
val outlineVariantDark = Color(0xFF41484D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDFE3E7)
val inverseOnSurfaceDark = Color(0xFF2C3134)
val inversePrimaryDark = Color(0xFF1A6585)
val surfaceDimDark = Color(0xFF0F1417)
val surfaceBrightDark = Color(0xFF353A3D)
val surfaceContainerLowestDark = Color(0xFF0A0F12)
val surfaceContainerLowDark = Color(0xFF171C1F)
val surfaceContainerDark = Color(0xFF1B2023)
val surfaceContainerHighDark = Color(0xFF262B2E)
val surfaceContainerHighestDark = Color(0xFF313539)